apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml

configMapGenerator:
  - name: pomerium-config
    files:
      - config.yaml

# Cert self-signed lab-only, xem ghi chú trong config.yaml.
secretGenerator:
  - name: pomerium-tls
    type: kubernetes.io/tls
    files:
      - tls-lab-only/tls.crt
      - tls-lab-only/tls.key
